services:
  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10


  report-db:
    image: postgres:16
    environment:
      POSTGRES_DB: reportdb
      POSTGRES_USER: report
      POSTGRES_PASSWORD: report
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${REPORT_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10


  statistics-db:
    image: postgres:16
    environment:
      POSTGRES_DB: statisticsdb
      POSTGRES_USER: statistics
      POSTGRES_PASSWORD: statistics
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${STATISTICS_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  inventory-db:
    image: postgres:16
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
      TZ: America/Argentina/Buenos_Aires
    ports: [ "5433:5432" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${INVENTORY_DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
