spring:
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://localhost:5436/reportdb
    username: report
    password: report
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        jdbc:
          time_zone: America/Argentina/Buenos_Aires
server:
  port: 8083

jwt:
  secret: miClaveSuperUltraMegaSecretaClaveDeJWT1234567890
