-- INSERT INTO user_entity (name, lastname, email, passwordhash, role, registrationdate, phone, address)
-- VALUES (
--            'Admin',
--            'Principal',
--            'email@gmail.com',
--            '$2a$12$KmGiNCC8zsMKeIqFhDBWrufUFJtdIlT4KPbm6VrPN1n.jfP3PaX46', -- hash de admin123
--            'ADMIN',
--            CURRENT_DATE,
--            '3510000000',
--            'Calle Falsa 123'
--        );
--
-- INSERT INTO user_entity (name, lastname, email, passwordhash, role, registrationdate, phone, address)
-- VALUES (
--            'Rodrigo',
--            'Moran',
--            'email@gmail.com',
--            '$2a$10$zWmboT0KjrZiEUzOSlUteeYzsVQEJvLu7MjbQGzV3Jc70SaACsP2G',
--            'CIUDADANO',
--            CURRENT_DATE,
--            '3510000000',
--            'Calle Falsa 123'
--        );

