spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://inventory-db:5433/inventorydb
    username: inventory
    password: inventory

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        jdbc:
          time_zone: America/Argentina/Buenos_Aires
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql

server:
  port: 8084

jwt:
  secret: miClaveSuperUltraMegaSecretaClaveDeJWT1234567890
